name: Pandoc Convert File

on: 
  workflow_call:
    inputs:
      inputPath:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      inputPath:
        default: 'README.md'
        required: false
        type: string
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files In Caller Repo
        uses: actions/checkout@v4.1.0
      - name: Checkout Styles In Tool Repo
        uses: actions/checkout@v4.1.0
        with:
          repository: Dreamer4o4/MarkdownResumeTool
          path: tool
          sparse-checkout: style
          sparse-checkout-cone-mode: false
      - name: Copy Style
        run: cp -r tool/style ./
      - name: Create Output Dir
        run: mkdir output
      - name: Convert Action
        uses: Dreamer4o4/MarkdownResumeTool@main
        with:
          inputPath: ${{ inputs.inputPath }} 
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          path: output
          
