name: Pandoc Convert File

on: 
  workflow_call:
    inputs:
      inputPath:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      inputPath:
        default: 'README.md'
        required: false
        type: string
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v4.1.0
      - name: Create Output Dir
        run: mkdir output
      - name: Convert Action
        uses: Dreamer4o4/MarkdownResumeTool@main
        with:
          inputPath: ${{ inputs.inputPath }} 
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          path: output
          
